## Q1:- Write a function so that the columns of the output matrix are powers of the input vector.

- The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

- **`HINT:`** Such a matrix with a geometric progression in each row is named for ``Alexandre-Theophile Vandermonde``.

In [5]:
import numpy as np 

In [6]:
x=np.array([1,2,3,4,5]) 
N=5 

In [12]:
matrix_1 = np.column_stack([x**(N-i-1) for i in range(N)]) 
print(matrix_1) 

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


##  OR 

In [13]:
matrix_2 = np.vander(x,N,increasing=False) 
print(matrix_2) 

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [15]:
# Compute the determinant of Matrix.

deter_1 = np.linalg.det(matrix_1) 
deter_2 = np.linalg.det(matrix_2)

print("Determinant of matrix 1:- ",deter_1)
print("Determitant of matrix 2:- ",deter_2)

Determinant of matrix 1:-  287.9999999999965
Determitant of matrix 2:-  287.9999999999965


- Hence The determitant for both the matrixs is the same

## Q2:- Write a function to find moving average in an array over a window:
- Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [99]:
def moving_average_fun(mylist):
    moving_average = []
    n = 0
    k = 3
    temp = 0
    length = len(mylist[:-3]) + 1
    while(n != length):
        for i in range(n,k):
            temp = mylist[i] + temp
        
        mv_avg = temp/3
        moving_average.append(mv_avg)
        temp = 0

        n += 1
        k += 1
    return moving_average


In [100]:
mylist =  [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
moving_average_fun(mylist)

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]